// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autossl/infrastructure/ent/cert"
	"autossl/infrastructure/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	certFields := schema.Cert{}.Fields()
	_ = certFields
	// certDescCreatedAt is the schema descriptor for created_at field.
	certDescCreatedAt := certFields[2].Descriptor()
	// cert.DefaultCreatedAt holds the default value on creation for the created_at field.
	cert.DefaultCreatedAt = certDescCreatedAt.Default.(func() time.Time)
	// certDescUpdatedAt is the schema descriptor for updated_at field.
	certDescUpdatedAt := certFields[3].Descriptor()
	// cert.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cert.DefaultUpdatedAt = certDescUpdatedAt.Default.(func() time.Time)
	// cert.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cert.UpdateDefaultUpdatedAt = certDescUpdatedAt.UpdateDefault.(func() time.Time)
}
